### ISSUE TITLE
Swift 教程 -> 基础部分 -> 可选绑定 小结 翻译与原文不一致

### ISSUE THREAD

**Issue by 313183373** [SwiftGGTeam/the-swift-programming-language-in-chinese#1003]
[文档链接](https://swiftgg.gitbook.io/swift/swift-jiao-cheng/01_the_basics#optional-binding)
翻译部分：
你可以包含多个可选绑定或多个布尔条件在一个 if 语句中，只要使用逗号分开就行。只要有任意一个可选绑定的值为 nil，或者任意一个布尔条件为 false，则整个 if 条件判断为 false，~~这时你就需要使用嵌套 if 条件语句来处理~~，如下所示：

**删除线部分内容在原文中并不存在，而且放在这里逻辑也不通。**

原文：
You can include as many optional bindings and Boolean conditions in a single if statement as you need to, separated by commas. If any of the values in the optional bindings are nil or any Boolean condition evaluates to false, the whole if statement’s condition is considered to be false. The following if statements are equivalent:

**Comment by numbbbbb** [comment]
感谢反馈，已修改！
