### ISSUE TITLE
Swift教程 -> 字符串和字符 -> 拓展字符串分隔符 小结中 使用了中文的"和#

### ISSUE THREAD

**Issue by 313183373** [SwiftGGTeam/the-swift-programming-language-in-chinese#1004]
[文档链接](https://swiftgg.gitbook.io/swift/swift-jiao-cheng/03_strings_and_characters#extended-string-delimiters)
如果需要字符串文字中字符的特殊效果，请匹配转义字符（\）后面添加与起始位置个数相匹配的 # 符。 例如，如果您的字符串是 ＃"Line 1 \nLine 2"＃ 并且您想要换行，则可以使用 **＃“Line 1 \#nLine 2”＃** 来代替。 同样，###"Line1 \###nLine2"### 也可以实现换行效果。

注意加粗部分

**Comment by numbbbbb** [comment]
感谢反馈，已修改！
