### ISSUE TITLE
“版本兼容性”章节翻译优化

### ISSUE THREAD

**Issue by lisaika** [SwiftGGTeam/the-swift-programming-language-in-chinese#1010]
当您使用 Xcode 11 构建 Swift 4 和 Swift 4.2 代码时，除了下面的功能仅支持 Swift 5.1，其他大多数功能都依然可用。
--> 当您使用 Xcode 11 构建 Swift 4 和 Swift 4.2 代码时，Swift 5.1 的大多数功能都适用。但以下功能仅支持 Swift 5.1 或更高版本:

这意味着，如果你将一个大的项目分解成多个框架（framework），你可以每次一个框架地迁移 Swift 4 代码到 Swift 5.1。
--> 这意味着，如果你将一个大的项目分解成多个框架（framework），你可以逐个地将框架从 Swift 4 代码迁移到 Swift 5.1。

**Comment by numbbbbb** [comment]
已更新，多谢反馈！
