### ISSUE TITLE
有一处变量名上下文不一致

### ISSUE THREAD

**Issue by TouchFriend** [SwiftGGTeam/the-swift-programming-language-in-chinese#1023]
问题：变量名上下文不一致
版本：Swift 5.1
链接：https://swiftgg.gitbook.io/swift/swift-jiao-cheng/02_basic_operators#nil-coalescing-operator
具体位置: Swift教程 -> 基本运算符 -> 空合运算符的最后
  如果你分配一个非空值（non-nil）给 userDefinedColorName，再次执行空合运算，运算结果为封包在 userDefaultColorName 中的值，而非默认值。

修改建议：userDefaultColorName应该是userDefinedColorName

**Comment by numbbbbb** [comment]
已修改，多谢反馈！
