### ISSUE TITLE
gitbook

### ISSUE THREAD

**Issue by NealChristmas** [SwiftGGTeam/the-swift-programming-language-in-chinese#1040]
你好，请问一下gitbook页面上面的头部header是怎么做出来的呢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by numbbbbb** [comment]
gitbook 后台可以设置：
![image](https://user-images.githubusercontent.com/2572987/76453970-cc7f4a00-63a1-11ea-836b-510e7f61edf3.png)

**Comment by NealChristmas** [comment]
使用gitbook-cli可以配置吗？部署到内网可以吗
