### ISSUE TITLE
“溢出运算符”跳转链接 404

### ISSUE THREAD

**Issue by opleonnn** [SwiftGGTeam/the-swift-programming-language-in-chinese#1046]
位置如图所示
![WechatIMG91](https://user-images.githubusercontent.com/48051254/81471583-b1f01280-9224-11ea-89c5-025d13ae42ee.png)

**Comment by numbbbbb** [comment]
语雀的跳转处理有问题，我和他们反馈一下。

**Comment by opleonnn** [comment]
还要支持语雀吗？不支持就把 Issue 关了

**Comment by numbbbbb** [comment]
语雀还没修复，在修复之前暂时先不上语雀。
