### ISSUE TITLE
部分github的链接404

### ISSUE THREAD

**Issue by moekyo** [SwiftGGTeam/the-swift-programming-language-in-chinese#1085]
git上的扩展阅读打开都基本404了，例如这个[构造过程中常量属性的修改](https://github.com/SwiftGGTeam/the-swift-programming-language-in-chinese/tree/bf8ac090d8135865d58635514a4ae36f3a8e8fb9/source/02_language_guide/14-Initialization.md#assigning-constant-properties-during-initialization)

**Comment by numbbbbb** [comment]
阅读请访问 [GitBook](https://swiftgg.gitbook.io/swift/)。GitBook 和 GitHub 的超链接格式有一些不同，不能同时支持。目前支持的是 GitBook，在 GitHub 直接点击确实不会正确跳转。

**Comment by moekyo** [comment]
> 阅读请访问 [GitBook](https://swiftgg.gitbook.io/swift/)。GitBook 和 GitHub 的超链接格式有一些不同，不能同时支持。目前支持的是 GitBook，在 GitHub 直接点击确实不会正确跳转。

我就是在GitBook上看的，可以试试https://swiftgg.gitbook.io/swift/swift-jiao-cheng/10_properties，存储属性那一节，就有两个跳转，第一个是GitBook内部跳转，没有问题。第二个是GitBook跳转到GitHub的，就404了。
