### ISSUE TITLE
阅读请访问 [GitBook](https://swiftgg.gitbook.io/swift/)。GitBook 和 GitHub 的超链接格式有一些不同，不能同时支持。目前支持的是 GitBook，在 GitHub 直接点击确实不会正确跳转。

### ISSUE THREAD

**Issue by moekyo** [SwiftGGTeam/the-swift-programming-language-in-chinese#1086]
阅读请访问 [GitBook](https://swiftgg.gitbook.io/swift/)。GitBook 和 GitHub 的超链接格式有一些不同，不能同时支持。目前支持的是 GitBook，在 GitHub 直接点击确实不会正确跳转。

_Originally posted by @numbbbbb in https://github.com/SwiftGGTeam/the-swift-programming-language-in-chinese/issues/1085#issuecomment-658748213_

我就是在GitBook上看的，可以试试https://swiftgg.gitbook.io/swift/swift-jiao-cheng/10_properties ，存储属性那一节，就有两个跳转，第一个是GitBook内部跳转，没有问题。第二个是GitBook跳转到GitHub的，就404了。

**Comment by numbbbbb** [comment]
这个链接确实写错了，已修复，还有类似问题可以再和我说。

**Comment by moekyo** [comment]
> 可以再和我说。

类似的错误基本每一章节都有，只要是跳转的GitHub的，都是404。
