### ISSUE TITLE
在 -> 再

### ISSUE THREAD

**Issue by github-xiaogang** [SwiftGGTeam/the-swift-programming-language-in-chinese#1087]
![image](https://user-images.githubusercontent.com/4679072/90875251-7512ea80-e3d3-11ea-9d36-aa839c3237b7.png)

**Comment by jevonmao** [comment]
”在“这里用的没错

但是这写的什么玩意？语句都不通顺是不是谷歌翻译的？正常人根本看不懂吧。

**Comment by numbbbbb** [comment]
已修改，包括翻译。
