### ISSUE TITLE
一些用词

### ISSUE THREAD

**Issue by duzean** [SwiftGGTeam/the-swift-programming-language-in-chinese#1091]
可不可把所有的“栗子”改成“例子”，这样看起来可能会感觉正式一点、严谨一点。

**Comment by numbbbbb** [comment]
文档翻译里似乎没有“栗子“
![image](https://user-images.githubusercontent.com/2572987/94808108-369b2300-03b6-11eb-9bb3-5365c415cb26.png)

你说的是网页文章翻译？那个可能有，是译者的喜好，不过分的情况下我们一般会保留。

**Comment by duzean** [comment]
啊是的，没有这个问题，在一个cnswift的网站看到就以为是这个项目，草率了。同一本的翻译，本项目专业很多。
