### ISSUE TITLE
从后往前看，列表的显示重复了

### ISSUE THREAD

**Issue by HSCOO** [SwiftGGTeam/the-swift-programming-language-in-chinese#1100]
如图操作：
![屏幕快照 2020-12-14 下午4 03 44](https://user-images.githubusercontent.com/7268774/102055743-46a79800-3e26-11eb-91fd-97354fbb68a2.png)
![屏幕快照 2020-12-14 下午4 03 56](https://user-images.githubusercontent.com/7268774/102055751-4ad3b580-3e26-11eb-877e-f7b874244070.png)
![屏幕快照 2020-12-14 下午4 01 23](https://user-images.githubusercontent.com/7268774/102055843-6b9c0b00-3e26-11eb-80e2-2a0bfa2e22b0.png)

**Comment by numbbbbb** [comment]
看了下，老文章确实有这个问题，但是没找到原因……tag的写法应该是正确的，可能是hexo有什么bug。
