### ISSUE TITLE
自动引用计数章节->解决实例之间的循环强引用->弱引用

### ISSUE THREAD

**Issue by yangyangnote** [SwiftGGTeam/the-swift-programming-language-in-chinese#1107]
文中两次出现
由于再也没有指向 Person 实例的强引用，该实例会被销毁
但根据上下文推测第二次出现应该改成
由于再也没有指向 Apartment 实例的强引用，该实例会被销毁
<img width="834" alt="截屏2021-02-03 下午3 44 21" src="https://user-images.githubusercontent.com/19338570/106714351-b112d280-6636-11eb-8923-094cfc59aa5a.png">

**Comment by numbbbbb** [comment]
已修改
