### ISSUE TITLE
内存安全章节-->属性的访问冲突---->最后一个代码片段描述

### ISSUE THREAD

**Issue by yangyangnote** [SwiftGGTeam/the-swift-programming-language-in-chinese#1108]
根据上下文看,"在实践中，大多数对于结构体属性的访问都会安全的重叠。例如，将上面例子里的变量 holly 改为本地变量而非全局变量，编译器就会可以保证这个重叠访问是安全的"

所以下面的例子应该改为

```
func someFunction() {
    var holly = Player(name: "Oscar", health: 10, energy: 10)
    balance(&holly.health, &holly.energy)  // 正常
}
```

更通畅

**Comment by numbbbbb** [comment]
这里原文就是如此：https://docs.swift.org/swift-book/LanguageGuide/MemorySafety.html。

读起来确实有点歧义，不过内容上来说也没错。【上面例子里的 holly】指的是前一个例子，冒号后面的例子想突出的是【本地变量】，放到一句话里确实容易混淆。
