### ISSUE TITLE
Language Reference - Declarations

### ISSUE THREAD

**Issue by WAMaker** [SwiftGGTeam/the-swift-programming-language-in-chinese#1129]
1. 第一个 GRAMMAR OF A DECLARATION 新增 actor-declaration
2. Type Variable Properties 节中的 GRAMMAR OF A VARIABLE DECLARATION 更新，链接确认
3. In-Out Parameters 节第五段（第一段代码上方的段落） 中删除 or to observe changes made by other code 这句话的翻译
4. Special Kinds of Parameters 节第三段第二句新增（A parameter that immediately follows a variadic parameter must have an argument label.or to observe changes made by other code）
5. Methods with Special Names 最后一段更新方法名
6. Throwing Functions and Methods 节第三段内容更新
7. Throwing Functions and Methods 节后新增 Asynchronous Functions and Methods
8. Functions that Never Return 节中的 GRAMMAR OF A FUNCTION DECLARATION 更新，链接确认
9. Enumeration Declaration 节第二段新增对 actor 的描述
10. Structure Declaration 节第二段新增对 actor 的描述
11. Class Declaration 节第二段新增对 actor 的描述
12. Class Declaration 节中 "Classes are reference types; instances of a class are referred to, rather than copied..." 段最后的链接有更新
13. Class Declaration 节后新增 Actor Declaration
14. Protocol Declaration 节最后 GRAMMAR OF A PROTOCOL DECLARATION 更新，链接确认
15. Initializer Declaration 节最后 GRAMMAR OF AN INITIALIZER DECLARATION 更新，链接确认
16. Subscript Declaration 节最后 GRAMMAR OF A SUBSCRIPT DECLARATION 更新，链接确认
17. Precedence Group Declaration 节最后 GRAMMAR OF A PRECEDENCE GROUP DECLARATION 更新，链接确认
18. Access Control Levels 节最后 GRAMMAR OF A DECLARATION MODIFIER 更新，链接确认

**Comment by SunsetWan** [comment]
> Throwing Functions and Methods 节第三段内容更新

**Comment by numbbbbb** [comment]
我觉得可以，保留吧。
