### ISSUE TITLE
您好，Swift教程 下的 并发 页面显示 This page is empty.

### ISSUE THREAD

**Issue by QiangXian** [SwiftGGTeam/the-swift-programming-language-in-chinese#1161]
您好，Swift教程 下的 并发 页面显示 This page is empty。仓库中的对应文件(source/02_language_guide/28_Concurrency.md)内无翻译文章，可能是更新时缺失了相应文件，请问是否能够重新上传一下，谢谢。

**Comment by numbbbbb** [comment]
这个章节是新内容，正在翻译中，对应issue #1136。
