### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by Elliot2636** [SwiftGGTeam/the-swift-programming-language-in-chinese#1163]
在这[一章](https://swiftgg.gitbook.io/swift/swift-jiao-cheng/20_extensions#initializers)中，里面 *值类型的构造器委托* 的链接失效，打开后报错。

<img width="783" alt="截屏2021-08-17 下午12 41 59" src="https://user-images.githubusercontent.com/45113206/129664825-c21ba316-8091-4ebd-a5a3-834e16d5034d.png">

<img width="933" alt="截屏2021-08-17 下午12 42 54" src="https://user-images.githubusercontent.com/45113206/129664889-88dacecf-ff6b-4e32-a9f8-10cabe7b71c1.png">

**Comment by numbbbbb** [comment]
已修改。这一章链接都有问题，统一处理了，感谢反馈。
