### ISSUE TITLE
字符串章节中 UTF-8 表格内容错位

### ISSUE THREAD

**Issue by VaslD** [SwiftGGTeam/the-swift-programming-language-in-chinese#1173]
<img width="756" alt="Screen Shot 2021-11-24 at 23 14 43" src="https://user-images.githubusercontent.com/3415065/143264803-f0054f23-5c9d-42d8-a00e-3fb62c2699d5.png">

可能是由于表格无法合并单元格，UTF-8 表格的列描述的内容与文字描述完全对应不上。

-----

另外，UT-8 和 UTF-16 章节着重于介绍 Swift String 中的字符与 UTF-8 和 UTF-16 集合中的元素无法一一对应，但 UTF-16 表格需要花一些时间（或者完整阅读解释文字）才能理解到 🐶 emoji 对应两个元素。

<img width="779" alt="Screen Shot 2021-11-24 at 23 18 54" src="https://user-images.githubusercontent.com/3415065/143265710-a52246fa-aa1c-41f2-b295-874fc6fe7d74.png">
 
如果 Markdown 渲染的网页表格不支持合并单元格的话，不如换成图片或代码块制表。

```plaintext
+========+===============+
|   ‼    |      🐶       |
+========+===============+
| U+203C | U+1F436       |
+--------+---------------+
| 8252   | 55357 | 56374 |
+--------+---------------+
```

**Comment by numbbbbb** [comment]
看了下，markdown 里的写法是对的，这里直接用了 HTML 写合并单元格。但是在部署的时候，gitbook 把 HTML 部分替换掉了，导致显示错误。加了两个截图上去。
