### ISSUE TITLE
 关于Swift 初见中三引号缩进

### ISSUE THREAD

**Issue by hiarcs** [SwiftGGTeam/the-swift-programming-language-in-chinese#1174]
当前译文：每行行首的缩进会被去除，直到和结尾引号的缩进相匹配
原文：Indentation at the start of each quoted line is removed, as long as it matches the indentation of the closing quotation marks. 

As long as 为“只要”而非“直到”，此处应指行如结尾引号有缩进，则每行行首将移除相同的缩进量。考虑如下代码：
`let quotation2 = """`
`[8空格]I said "I have \(apples) apples."`
`[4空格]And then I said "I have \(apples + oranges) pieces of fruit."`
`[4空格] """`

`let quotation3 = """`
`[4空格] I said "I have \(apples) apples."`
`[4空格] And then I said "I have \(apples + oranges) pieces of fruit."`
`[4空格] """`

两者结尾引号的缩进相同，如为“直到……匹配”，则两者输出应相同，实际前者有缩进，后者无。

**Comment by kevinsan** [comment]
已收到您的邮件，我会在24小时内回复您的。——Kevin San.

**Comment by yjh883** [comment]
您好，我已经收到了您的邮件，会尽快给您回复哒。

**Comment by illuer** [comment]
您好，你的邮件已收到。谢谢！

**Comment by numbbbbb** [comment]
已修改
