### ISSUE TITLE
Swift初见-枚举值

### ISSUE THREAD

**Issue by hiarcs** [SwiftGGTeam/the-swift-programming-language-in-chinese#1176]
原文：The case values of an enumeration are actual values
译文：枚举的关联值是实际值

我认为这里的case value不是后面提到的values associated with the case—these values are determined when you make the instance, and they can be different for each instance of an enumeration case。因此可直译为case关键字后的值或简称枚举值，否则读到后面关联值的部分会形成误导。

**Comment by numbbbbb** [comment]
已修改，多谢指出，
