### ISSUE TITLE
SwiftGG 与 Apple 开发者文档术语差异

### ISSUE THREAD

**Issue by VaslD** [SwiftGGTeam/the-swift-programming-language-in-chinese#1180]
Apple 开发者文档已经逐渐在写[官方中文版](https://developer.apple.com/cn/documentation)，术语是否考虑和官方翻译对齐？

比如：结构 (structure) vs. 结构体；遵从 (conformance) vs. 遵循；浮点值 (float) vs. 浮点数。

**Comment by yjh883** [comment]
您好，我已经收到了您的邮件，会尽快给您回复哒。

**Comment by illuer** [comment]
您好，你的邮件已收到。谢谢！

**Comment by SketchK** [comment]
@VaslD 感谢提醒，未来我们会考虑这部分情况
