### ISSUE TITLE
swift教程/字符串与字符

### ISSUE THREAD

**Issue by Wizard23333** [SwiftGGTeam/the-swift-programming-language-in-chinese#1192]
原文：The escaped special characters \0 (null character), \\ (backslash), \t (horizontal tab), \n (line feed), \r (carriage return), \" (double quotation mark) and \' (single quotation mark)
译文：转义字符 \0(空字符)、\\(反斜线)、(水平制表符)、(换行符)、(回车符)、\"(双引号)、\'(单引号)。

使用google翻译有概率复现相同的错误

**Comment by SketchK** [comment]
@Wizard23333 欢迎提交 PR
