### ISSUE TITLE
escaping 特性翻译错误

### ISSUE THREAD

**Issue by honeyeeb** [SwiftGGTeam/the-swift-programming-language-in-chinese#1196]
[@escaping](https://swiftgg.gitbook.io/swift/yu-yan-can-kao/07_attributes#escaping) 的特性翻译严重错误

英文原文：
> the parameter’s value can be stored for later execution. This means that the value is allowed to outlive the lifetime of the call.

译文：
> 它表示参数将不会被存储以供延迟执行。这将确保参数不会超出函数调用的生命周期。

**Comment by SketchK** [comment]
@honeyeeb 欢迎提交 PR
