### ISSUE TITLE
Swift5.7关于并发性部分代码段缺乏{}并且没有严格按照官方文档空格

### ISSUE THREAD

**Issue by chaoStrength** [SwiftGGTeam/the-swift-programming-language-in-chinese#1203]
/source/01_welcome_to_swift)/03_a_swift_tour.md该文件并发性一节中：`func fetchUserID(from server: String) async -> Int`函数的函数体缺乏部分{}。并且这三个函数的函数名和函数体之间的大括号之间缺乏空格，没有严格按照官方文档来排版。

**Comment by SketchK** [comment]
@chaoStrength 感谢提醒，欢迎修正并提交 PR

**Comment by SketchK** [comment]
@chaoStrength 感谢提醒，欢迎修正并提交 PR

**Comment by SketchK** [comment]
@chaoStrength 感谢提醒，欢迎修正并提交 PR
