### ISSUE TITLE
Swift教程-闭包-值捕获 翻译错误

### ISSUE THREAD

**Issue by areslk** [SwiftGGTeam/the-swift-programming-language-in-chinese#1225]
- 原文：The closure expression also specifies a return type of String, to indicate the type that will be stored in the mapped output array.
- 译文：闭包表达式指定了返回类型为 String，以表明存储映射值的新数组类型为 String。

新数组类型应该为[String]   而不是String
或者这样翻译：闭包表达式还指定了返回类型为 String，以表示将存储在映射后的新数组中元素的类型为String。

**Comment by SketchK** [comment]
@areslk 欢迎提交 PR 呀

**Comment by EyreFree** [comment]
@bnbfly
