### ISSUE TITLE
“Swift 初见”篇，“下载 Playground“链接失效

### ISSUE THREAD

**Issue by linxuanqing** [SwiftGGTeam/the-swift-programming-language-in-chinese#1226]
“Swift 初见”篇，“下载 Playground“链接失效：
404
Not Found
The requested URL was not found on this server.

**Comment by numbbbbb** [comment]
看了下，官方文档已经删掉了这个例子，更新了内容，和官方保持一致。
<img width="1112" alt="CleanShot 2023-03-29 at 10 28 39@2x" src="https://user-images.githubusercontent.com/2572987/228589567-56477384-b993-486b-ad11-07877a1d6ab6.png">
