### ISSUE TITLE
Adding dark mode. 

### ISSUE THREAD

**Issue by Abhishek-465** [SwiftGGTeam/the-swift-programming-language-in-chinese#1240]
I can add dark mode with the help of CSS and javascript which will be great for reading.

**Comment by ZainabR11** [comment]
I have a vision to enhance user experience by implementing dynamic features like dark mode using CSS and JavaScript. This not only aligns with the current trends but also showcases my commitment to continuously improve and innovate.

**Comment by SketchK** [comment]
@ZainabR11 @Abhishek-465 
Good Idea! 
Go Ahead!
You can do anything you want and waiting for your pull request!

**Comment by ZainabR11** [comment]
@SketchK 
Please assigned the task. As it is for our hacktober 2023.

**Comment by ZainabR11** [comment]
Is this issue closed? @SketchK

**Comment by ZainabR11** [comment]
@SketchK if it is not closed i want to make pull request

**Comment by SketchK** [comment]
> @SketchK if it is not closed i want to make pull request

 not closed yet.

**Comment by ZainabR11** [comment]
@SketchK  Kindly assist as it is for the hacktoberfest 2023. This contribution can make a big contribution for me.

**Comment by SketchK** [comment]
Hi, @ZainabR11 
I saw your demo in this #1241 , While the content in the video demonstrates that a site can switch between dark/light modes, I ran your PR locally and it will not work for our site style.

The reason I repeatedly told you about the demo video in the PR is that I was hoping you could prove that the dark/light mode switching was actually present on our site when we merged in your PR.

Also, our site uses the default styles provided on GitBook, and it is essentially impossible to change the styles unless we don't use GitBook's hosting service. This would be one of the reasons why your PR won't affect the final presentation.

I left you a message saying that we could communicate via WeChat to clarify this issue, and that we have plans to migrate the entire site from GitBook in the future, but not right now.

I hope you understand that we can't do a merge if the PR doesn't make a difference to the actual presentation of the site.
