### ISSUE TITLE
LanguageGuide / protocols.md ⭐️⭐️⭐️⭐️⭐️

### ISSUE THREAD

**Issue by zhangqifan** [SwiftGGTeam/the-swift-programming-language-in-chinese#1331]
翻译文件：https://github.com/SwiftGGTeam/the-swift-programming-language-in-chinese/blob/swift-6-beta-translation/swift-6-beta.docc/LanguageGuide/Protocols.md
请查看 Markdown 文件内容获得对应的 Swift 原文档链接和翻译预估时长

**Comment by Saafo** [comment]
@zhangqifan 这个还没翻译完，应该是 In Progress，估计得下周才能翻译完

**Comment by Saafo** [comment]
搞定了
