### ISSUE TITLE
The main branch does not have a source directory. How should I modify the document?

### ISSUE THREAD

**Issue by resetsix** [SwiftGGTeam/the-swift-programming-language-in-chinese#1401]
I didn't find the source directory in the main branch.

<img width="1320" alt="图片" src="https://github.com/user-attachments/assets/5cda0068-7d4d-44a1-a951-d7ac5bcd6bf2">

I will correct the following documents and more.

![图片](https://github.com/user-attachments/assets/f19ad2bc-a99e-4fae-83ff-1f7067f4d0fb)

**Comment by king-open** [comment]
It is in the folder `swift-6-beta.docc`, and I have already submitted the PR.
