### ISSUE TITLE
epub版本无法加载图片

### ISSUE THREAD

**Issue by evindu** [SwiftGGTeam/the-swift-programming-language-in-chinese#585]
![](http://d.pr/LmPT)
只显示图片编号

**Comment by evindu** [comment]
我在ios9 的手机上也试了一下，发现也是一样的问题 可以排除是系统问题

**Comment by liuzhiyi1992** [comment]
朋友是怎样将这本是加入到书库的？直接搜索还是下载？

**Comment by evindu** [comment]
@liuzhiyi1992  就是itunes啊 我macbook 上用ibooks上看 然后itunes 同步过去的

**Comment by tangyi** [comment]
还是不能显示图片

**Comment by numbbbbb** [comment]
@floydzhang315
