### ISSUE TITLE
【术语表】请大家提出建议

### ISSUE THREAD

**Issue by numbbbbb** [SwiftGGTeam/the-swift-programming-language-in-chinese#62]
下面是我收集的术语表及其备选翻译，大家可以进行补充或者提出合适的翻译，这个表将被用于校对。

带“*”号的是争议比较大的，请大家重点关注。

| 术语 | 备选翻译 |
| --- | --- |
| associatedtype | 关联类型 |
| range | 区间 |
| type property | 类型属性 |
| Unary operator | 一元运算符 |
| Binary operator | 二元运算符 |
| Ternary operator | 三元运算符 |
| Labeled Statement | 具名语句 |
| conform Protocol | 遵循协议 |
| availability-condition | 可用性条件 |
| fallthrough | 贯穿 |
| Branch Statement | 分支语句 |
| Control Transfer Statement | 控制传递语句 |
| Type Annotation | 类型标注 |
| Type Identifier | 类型标识符 |
| Metatype Type | 元类型 |
| Protocol Composition Type | 复合协议类型 |
| associated value | 关联值 |
| raw value | 原始值 |
| computed property | 演算属性 |
| stored property | 寄存属性 |
| calculate property | 演算属性 |
| operator | 运算符 |
| playground | 代码预览 |
| array | 数组 |
| dictionary | 字典 |
| list | 列表 |
| statement | 语句 |
| expression | 表达式 |
| \* optional | 可选 |
| \* Implicitly Unwrapped optional | 隐式解析可选 |
| \* Optional Binding | 可选绑定 |
| \* optional chaining | 可选链 |
| collection | 集合 |
| convention | 约定 |
| iterate | 迭代 |
| nest | 嵌套 |
| Inheritance | 继承 |
| override | 重写 |
| base class | 基类 |
| \* Designated Initializer | 指定构造器 |
| \* Convenience Initializer | 便利构造器 |
| Automatic Reference Counting | 自动引用计数 |
| type inference | 类型推断 |
| \* Type Casting | 类型检查 |
| \* unwrapped | 解析 |
| \* wrapped | 未解析 |
| \* note | 注意 |
| closure | 闭包 |
| tuple | 元组 |
| first-class | 一等 |
| \* deinitializer | 析构器 |
| \* Initializer | 构造器 |
| \* initialization | 构造过程 |
| \* deinitialization | 析构过程 |
| \* getter | 不翻译 |
| \* setter | 不翻译 |
| \* subscript | 下标脚本或下标 |
| property | 属性 |
| attribute | 如果指以`@`开头的语法，翻译为特性，其他情况翻译为属性 |
| method | 方法 |
| Enumeration | 枚举 |
| Structure | 结构体 |
| Protocol | 协议 |
| Extension | 扩展 |
| Generic | 泛型 |
| \* literal value | 字面量 |
| alias | 别名 |
| Assertion | 断言 |

**Comment by Lenhoon** [comment]
Type Annotation 感觉翻译成类型标注更好些吧，wiki上也是这样解释地

**Comment by athenaxing** [comment]
type property	类属性   是不是可以改成类型属性 与后面的翻译保持一致？

**Comment by athenaxing** [comment]
first-class	一等  翻译成 一级或第一类？

**Comment by numbbbbb** [comment]
@athenaxing 类型属性确实更好些，一等的翻译主要是延续传统。

**Comment by Lenhoon** [comment]
Override是译为覆盖更好一些还是重写更好一些呢？

**Comment by aiiaji** [comment]
重写吧，动词动作更加明显一点，覆盖更像是产生的效果
 
------------------
  Thanks and best regards!  
  王浩力
 
  18581863091
 
  E-mail: aiiaji.vip@foxmail.com 
 
  MSN：aiiaji@live.cn 

  程序构建是一门艺术，我在不断探寻.





 




------------------ 原始邮件 ------------------
发件人: "Lenhoon"<notifications@github.com>; 
发送时间: 2015年6月30日(星期二) 上午10:40
收件人: "numbbbbb/the-swift-programming-language-in-chinese"<the-swift-programming-language-in-chinese@noreply.github.com>; 
抄送: "ABA"<14606345@qq.com>; 
主题: Re: [the-swift-programming-language-in-chinese] 【术语表】请大家提出建议 (#62)




Override是译为覆盖更好一些还是重写更好一些呢？
 
&mdash;

**Comment by KYawn** [comment]
convention 是译为公约？ 或者 惯例？

**Comment by LhiKien** [comment]
是约定吧？

发自我的 iPhone

**Comment by KYawn** [comment]
嗯，好的。我看前面的文章，翻译的也是约定。

**Comment by littledogboy** [comment]
availability-condition  可用性条件
用来检查你想要使用的接口是否可用

**Comment by TJRoger** [comment]
fallthrough(代碼)不翻譯
calculate property 計算（動詞）屬性（，定為術語合適麼）
playground （不太好翻譯）（代碼預覽 不如）代碼操場/代碼訓練場
optional 可選的（形容詞）
Type Casting 類型映射/轉換
first-class 初類
initialization 構造
deinitialization 析構
getter/setter 代碼中不翻譯，getter （method） 取值（方法），setter（method) 設值
（方法）assertion 斷點
另外術語請去掉各種變形（複數、過去式等)

**Comment by LhiKien** [comment]
assertion 不是断点，是断言吧？

**Comment by LhiKien** [comment]
playground可以不翻译的，本意就是演练场

**Comment by jameslan** [comment]
Playground 是游乐场。 不是那种大型游乐场，是给小孩玩的，比如幼儿园里面，比如公园里面，或者有些商场里面：有滑梯，攀登架等等设施

**Comment by TJRoger** [comment]
刚刚搜索了下全书，`first-class` 在全书中出现三次，两次是 `first-class type`, 一次是`first-class support`.
个人觉得可以把·``first-class type`定为术语，译为基础类型/第一类类型/元类型/第一阶类型，另外一处按照本意翻译成`一流/顶级/一等支持`即可。
把`first-class`定为术语不太合适，在英文中用连字符连接形成形容词词性，基本上没有把形容词定为术语的吧
参考维基百科：
[first-class citizen](https://en.wikipedia.org/wiki/First-class_citizen)  
[第一类对象](https://zh.wikipedia.org/wiki/%E7%AC%AC%E4%B8%80%E9%A1%9E%E7%89%A9%E4%BB%B6)
```
In programming language design, a first-class citizen (also object, entity, or value) in a given programming language is an entity which supports all the operations generally available to other entities. These operations typically include being passed as a parameter, returned from a function, and assigned to a variable.
```
```
第一类物件（英语：First-class object）在电脑科学中指可以在执行期创造并作为参数传递给其他函数或存入一个变数的实体[1]。将一个实体变为第一类物件的过程叫做“物件化”（Reification）[2]。
“第一类物件”这一名称最早由Christopher Strachey在1960年代发明，原称“第一类公民”（First-class citizen），意指函数可作为电脑语言中的第一类公民。英文中也称“First-class entity”或“First-class value”。
```
[first-class function](https://en.wikipedia.org/wiki/First-class_function)
```
In computer science, a programming language is said to have first-class functions if it treats functions as first-class citizens. Specifically, this means the language supports passing functions as arguments to other functions, returning them as the values from other functions, and assigning them to variables or storing them in data structures.[1] Some programming language theorists require support for anonymous functions (function literals) as well.[2] In languages with first-class functions, the names of functions do not have any special status; they are treated like ordinary variables with a function type.
```
[头等函数](https://zh.wikipedia.org/wiki/%E5%A4%B4%E7%AD%89%E5%87%BD%E6%95%B0)
```
头等函数（first-class function）是指在程序设计语言中，函数被当作头等公民。这意味着，函数可以作为别的函数的参数、函数的返回值，赋值给变量或存储在数据结构中。
```

**Comment by LEOYoon-Tsaw** [comment]
原文 | 译文
----- | -----
labeled statements | 具名语句
fallthrough | 穿透
protocol composition type | 复合协议类型
raw value | 原值
computed property | 演算属性
stored property | 寄存属性
calculate property | 演算属性
playground | 游乐场
optional | 或有
implicitly unwrapped optional | 自解封或有
unwrapped | 解封
optional binding | 或有绑定
optional chaining | 链式或有
iterate | 遍历
override | 覆盖
designated initializer | 指定构造器
convenience initializer | 轻构造器
observator | 触发器
getter | 读值器
setter | 赋值器
subscript | 下标
literal value | 书写量

**Comment by sunshineclt** [comment]
个人觉得wrapped用封装翻译不太好吧。。。封装是面向对象的概念，而且词性也不对，wrapped应该翻译成“未解析”的比较好吧

**Comment by numbbbbb** [comment]
@sunshineclt 已修改，和其他术语统一。

**Comment by WXGBridgeQ** [comment]
enum 中的 case，感觉翻译成`用例`比较好，之前有人翻译成`事件`。

**Comment by TJRoger** [comment]
@sunshineclt `wrapped`你说词性不对我是认可的，但是你说翻译成`未解析`也不好吧，翻译成`未解析的`还差不多，关键是词性问题，翻译成`已封装的`也没什么问题 @numbbbbb

**Comment by TJRoger** [comment]
@WXGBridgeQ enum中的case是关键字为什么要翻译啊？是准备做编译器么？

**Comment by WXGBridgeQ** [comment]
@TJRoger 是我没说清楚，我指的是文档中出现的`enumeration cases`，翻译成`枚举用例`好一些。

**Comment by HermitCarb** [comment]
wrapped？每个词只能对应一种汉语意思么？
其实英语里意思差不太多，但到汉语，为了尽量精确的描述，感觉提供几个可选的意思供翻译时选择比较好。
再说装箱/封装和未解析，在汉语意思差别有点大吧。如果在翻译过程中一味的想要统一……

**Comment by jasine** [comment]
建议加入swift2.2 中增加的`associatedtype`关键字`关联类型`

**Comment by ApolloZhu** [comment]
建议
argument label 从 “参数标签” 改译为 “实参标签”
parameter name 从 “参数名称” 改译为 “形参名称”
