### ISSUE TITLE
请问会发布mobi版的离线版电子书吗？

### ISSUE THREAD

**Issue by yangchao0033** [SwiftGGTeam/the-swift-programming-language-in-chinese#620]
`我kindle用的多一些😁，但是他对PDF和ePub不友好~，排版很尴尬😂`
**向各位参与翻译的开发表示无尽的敬意！**

**Comment by numbbbbb** [comment]
这个得问极客学院的开发了，目前部署在他们的 Wiki 系统上。@floydzhang315
