### ISSUE TITLE
3.1版有计划做翻译吗？

### ISSUE THREAD

**Issue by yangkile** [SwiftGGTeam/the-swift-programming-language-in-chinese#690]

**Comment by fresherman1723** [comment]
I am still a fresher on this，what do u want about it？I may try my best.




------------------ 原始邮件 ------------------
发件人: "yangkile";<notifications@github.com>;
发送时间: 2017年3月30日(星期四) 下午3:22
收件人: "numbbbbb/the-swift-programming-language-in-chinese"<the-swift-programming-language-in-chinese@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [numbbbbb/the-swift-programming-language-in-chinese] 3.1版有计划做翻译吗？ (#690)

**Comment by longjing2000** [comment]
最近有翻译计划没？

**Comment by SketchK** [comment]
@longjing2000 正在校对

**Comment by longjing2000** [comment]
哦，还以为可以参与翻译。谢谢。

**Comment by SketchK** [comment]
@longjing2000 欢迎参与，这是一个开源项目

**Comment by Creatisan** [comment]
请问3.1何时会更新？

**Comment by magicdict** [comment]
难道准备WWDC2017之后开始？
