### ISSUE TITLE
Swift4.0 可以开始翻译了

### ISSUE THREAD

**Issue by magicdict** [SwiftGGTeam/the-swift-programming-language-in-chinese#702]
苹果已经发布了Swift4.0，什么时候开始启动翻译计划呢。
准备给公司进行培训，希望能直接用Swift4.0

**Comment by Creatisan** [comment]
3.1还没有发布，4.0估计还得一阵子

**Comment by sing-crystal** [comment]
Swift 4 已经发布了，在 Xcode 9 上可以用 Swift 4. @Creatisan

**Comment by sing-crystal** [comment]
正在准备中，近期启动 Swift 4.0 的翻译 @magicdict

**Comment by Creatisan** [comment]
我的意思的翻译3.1版本还没发布，哈哈，期待3.1快点发布 @sing-crystal

**Comment by sing-crystal** [comment]
我们有可能不翻译 Swift 3.1 了。直接翻译最新的 Swift 4。 @Creatisan

**Comment by Creatisan** [comment]
@sing-crystal 谢谢告知，我还是安心的学习3.0了。

**Comment by One1Light** [comment]
点个赞，支持一下

**Comment by ann2bad** [comment]
大神们加油

**Comment by wilsonandusa** [comment]
@sing-crystal 请问如何参与4.0的翻译呢？

**Comment by JolieYang** [comment]
同上

**Comment by bqlin** [comment]
现在[官网](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/BasicOperators.html#//apple_ref/doc/uid/TP40014097-CH6-XID_109)的是 swift 4 的，能否对照翻译校对？

**Comment by zhongdom** [comment]
4.0正式发布了，什么开始组织翻译呢？

**Comment by magicdict** [comment]
新增了一个章节，需要整章翻译，同时，文章次序也需要更改一下。

**Comment by shanksyang** [comment]
@magicdict 我在issue里面建了所有章节的翻译issue，每个人可以单独认领进行翻译

**Comment by WhistlingArrow** [comment]
我加QQ群了 怎么一直没通过呢

**Comment by DoubleHH** [comment]
hi，如何参与翻译呀，还需要人么？

**Comment by ZexiFangkong** [comment]
👍
