### ISSUE TITLE
极客学院的PDF严重落后于Github的最新版本

### ISSUE THREAD

**Issue by magicdict** [SwiftGGTeam/the-swift-programming-language-in-chinese#703]
极客学院是不是不维护PDF版本了，下载的东西已经远远落后于Github了。
能不能请他们更新一下PDF版本，最近在授课的时候，只能看英语原文授课了。。。

**Comment by Creatisan** [comment]
如何自己生成PDF，我发现极客学院的PDF，缺少很多图。所以想自己生成PDF。

**Comment by larny** [comment]
官网有最新iBook版本的

**Comment by magicdict** [comment]
iBook大陆地区没有办法使用，然后，估计中文新的PDF没有
