### ISSUE TITLE
Swift4.0 Translation-Language Guide-Error Handling

### ISSUE THREAD

**Issue by shanksyang** [SwiftGGTeam/the-swift-programming-language-in-chinese#725]

**Comment by kemchenj** [comment]
占

**Comment by github641** [comment]
目前版本的翻译：Swift 提供了在运行时对可恢复错误的抛出、捕获、传递和操作的一等公民支持。
Swift provides first-class support for throwing, catching, propagating, and manipulating recoverable errors at runtime.
first-class support 翻译为“一等公民支持”不合适吧，是否翻译为“优秀的支持、良好的支持等等”好一些呢？

**Comment by calvingit** [comment]
在计算机领域，“first-class” 翻译成“一等公民”已经成为惯用词了。在其他语言里面，first-class 常用于形容函数，看[Google搜索结果](https://www.google.com/search?newwindow=1&q=%E5%87%BD%E6%95%B0+%E4%B8%80%E7%AD%89%E5%85%AC%E6%B0%91&oq=%E4%B8%80%E7%AD%89%E5%85%AC%E6%B0%91&gs_l=psy-ab.3.1.0j0i5i30k1l2.243067.245212.0.248585.12.9.0.0.0.0.621.1650.4-1j2.3.0....0...1.1j4.64.psy-ab..10.2.1050....0.eKuqTYs2hvA)。

first-class 强调first，已经是第一，没有上升空间了。假如翻译成“优秀”、“良好”，其实离first的 💯 还有一段距离。所以翻译不能为了语句更通顺，更符合中文的习惯，就强行把原文的神韵改变了。

**Comment by github641** [comment]
@calvingit 学习了
