### ISSUE TITLE
Swift4.0 Translation-Language Guide-Methods

### ISSUE THREAD

**Issue by shanksyang** [SwiftGGTeam/the-swift-programming-language-in-chinese#731]

**Comment by kemchenj** [comment]
占

**Comment by liuyanhongwl** [comment]
`struct Point {
    var x = 0.0, y = 0.0
    func isToTheRightOfX(_ x: Double) -> Bool {
        return self.x > x
    }
}
let somePoint = Point(x: 4.0, y: 5.0)
if somePoint.isToTheRightOfX(1.0) {
    print("This point is to the right of the line where x == 1.0")
}`

其中 `if somePoint.isToTheRightOfX(1.0) {` 应该改成 `if somePoint.isToTheRightOfX(x: 1.0) {`

**Comment by liuyanhongwl** [comment]
```
struct Point {
    var x = 0.0, y = 0.0
    mutating func moveByX(deltaX: Double, y deltaY: Double) {
        x += deltaX
        y += deltaY
    }
}
var somePoint = Point(x: 1.0, y: 1.0)
somePoint.moveByX(2.0, y: 3.0)
```
其中 `    mutating func moveByX(deltaX: Double, y deltaY: Double) {` 应该改成 `    mutating func moveByX(_ deltaX: Double, y deltaY: Double) {`

**Comment by SketchK** [comment]
@liuyanhongwl 谢谢指正，不如提个 PR 
: ]
