### ISSUE TITLE
关于所谓的“支付宝红包”邮件提醒

### ISSUE THREAD

**Issue by numbbbbb** [SwiftGGTeam/the-swift-programming-language-in-chinese#839]
因为很多人都收到了提醒，这里说明一下，那个支付宝邮件并不是我们发送的，是某个公司抓取大家的 GitHub 邮箱进行群发。

很多开源项目都遇到了类似的情况，比如：[这个 issue](https://github.com/ruanyf/es6tutorial/issues/750)。请大家擦亮双眼，不要上当受骗。

**Comment by BigNerdCoding** [comment]
薅羊毛都到这种地步了，服了
