### ISSUE TITLE
Swift5.0 ReferenceManual Statements 章节更新

### ISSUE THREAD

**Issue by BigNerdCoding** [SwiftGGTeam/the-swift-programming-language-in-chinese#875]
https://docs.swift.org/swift-book/ReferenceManual/Statements.html

位于 chapter3 下面

**Comment by Byelaney** [comment]
非 team member 可以认领翻译吗？

**Comment by numbbbbb** [comment]
可以，这个项目面向所有人。

**Comment by Byelaney** [comment]
谢谢回答，那在认领了之后有 deadline 之类的么？

**Comment by numbbbbb** [comment]
时间比较自由，质量是最重要的。我大概看了一下，这块改动可能还比较多，所以时间上不用太着急。
不过这块需要细心一点，因为是基于之前的版本更新，如果不注意可能会漏掉改动的内容。
虽然没有硬性的时间，不过如果时间太长还没有提交（比如超过一个月），那可能会被当做已经放弃，再由其他人认领。如果内容改动比较多，可以适当在这里同步进度，这样其他人就知道还在继续翻译。

**Comment by Byelaney** [comment]
再次感谢，那我第一次认领一下翻译 🙇

**Comment by numbbbbb** [comment]
我觉得可以，术语表我已经更新了。
这里需要注意一下，做一个全书内容的搜索，把所有老的翻译都改成新的，否则不一致会让读者不好理解。
