### ISSUE TITLE
Swift5.0 ReferenceManual zzSummaryOfTheGrammar 更新

### ISSUE THREAD

**Issue by BigNerdCoding** [SwiftGGTeam/the-swift-programming-language-in-chinese#880]
https://docs.swift.org/swift-book/ReferenceManual/zzSummaryOfTheGrammar.html

chapter3 下面

**Comment by Adolf-L** [comment]
认领

**Comment by Adolf-L** [comment]
https://github.com/SwiftGGTeam/the-swift-programming-language-in-chinese/pull/911
#911

**Comment by numbbbbb** [comment]
翻译完成，我合并完成后来 close。
