### ISSUE TITLE
在线阅读现在部署到哪个网站了？

### ISSUE THREAD

**Issue by Latias94** [SwiftGGTeam/the-swift-programming-language-in-chinese#899]
极客学院wiki现在还是老版本的 [wiki](https://github.com/SwiftGGTeam/the-swift-programming-language-in-chinese/issues/821)
[http://swiftguide.cn/](http://swiftguide.cn/) 也找不到文档
能不能提供一个自动部署的平台提供读者阅读？
或者提供一个离线转换 PDF 的方式？

**Comment by BigNerdCoding** [comment]
@Latias94 等这次翻译结束可能会使用 GitHub Pages ，我们需要确定下效果，请耐心等待一下。

**Comment by numbbbbb** [comment]
非常感谢对文档翻译的关注。
极客学院那边更新速度太慢，我们正在重新部署和测试。
Swift 5 剩下的任务已经不多了，我们会在更新到 5 之后和新部署的网址一起通知大家，到时 swiftguide 那边我也会联系去更新跳转。

**Comment by Latias94** [comment]
@BigNerdCoding @numbbbbb 感谢回复，感谢所有参与者的贡献。

**Comment by iHTCboy** [comment]
@numbbbbb 感谢所有贡献者，请问有没有考虑提供 ePub版下载啊？我比较喜爱用 iBook 看书
