### ISSUE TITLE
01_the_basics的一个小错误

### ISSUE THREAD

**Issue by guo-c14** [SwiftGGTeam/the-swift-programming-language-in-chinese#922]
https://swiftgg.gitbook.io/swift/swift-jiao-cheng/01_the_basics#enforcing-preconditions

第三段的precondition(_:_:file:line:)应该改为preconditionFailure(_:file:line:)

**Comment by BigNerdCoding** [comment]
@guo-c14  了解，等会下班回去弄

**Comment by numbbbbb** [comment]
@BigNerdCoding 我改好了。
