### ISSUE TITLE
Chapter2-Opaque Types

### ISSUE THREAD

**Issue by Nemocdz** [SwiftGGTeam/the-swift-programming-language-in-chinese#943]
新增的章节。

https://docs.swift.org/swift-book/LanguageGuide/OpaqueTypes.html

**Comment by numbbbbb** [comment]
新增章节要注意链接跳转问题，本章节内部跳转其他章节，其他章节跳转本章节，文件名一定要写对。
按照原文档顺序，这个章节是插在中间，但是如果这样新增，后续的章节序号都要+1，导致正文中所有跳转链接都要修改。
因此这个章节的文件名序号不要插到中间，直接放到最后。目前第二章有 26 个章节，这个文件名就是 27_Opaque_Types.md。

**Comment by Nemocdz** [comment]
这个新章节可能会出现一些新术语，新术语的翻译待定。定下来后会更新到术语表中。

**Comment by Nemocdz** [comment]
术语表已更新
