### ISSUE TITLE
构造过程中安全检查4的问题

### ISSUE THREAD

**Issue by xiaoLit** [SwiftGGTeam/the-swift-programming-language-in-chinese#968]
在《构造过程》中“安全检查4”对比了英文的原文发现意思相同
![image](https://user-images.githubusercontent.com/13831437/61262675-a70d5280-a7b8-11e9-93fb-67cb0e954a6f.png)

但实际上并不绝对。
![image](https://user-images.githubusercontent.com/13831437/61265496-f9ec0780-a7c2-11e9-82fc-8d8cdf830a3c.png)
这里可以看到红框代码在父类初始化代码之前，处于构造方法第一阶段中。与官方文档说“构造器在第一阶段构造完成之前，不能调用任何实例方法，不能读取任何实例属性的值”不符合。该图相当于一个实例变量被初始化了，就能立即使用了，那怕这个实例还没有完全被初始化。有些不解...

**Comment by numbbbbb** [comment]
属性不能读取，可以赋值。所以你这里第一行的赋值能执行是没问题的。
至于读取，你这种写法读取的应该不是`self.have`，是`init()`传入的参数`have`，所以没有问题，这不是读取实例属性。如果改成`"test\(self.have)"`应该就不行了。

**Comment by BigNerdCoding** [comment]
@xiaoLit 原文没错，你的例子是错的。

所有 

```
self.have = have 
```

不是实例方法，也不是实例属性的读操作而是赋值操作。如果你把代码改成:

```
class tree {
    var num: Int?
    var name: String
    init(name: String) {
        self.name = name
    }
}

class appleTree: tree {
    var have: Bool
    init(name: String, num: Int, have: Bool) {
        let temp = self.have
        super.init(name: name)
    }
}
```

此时才是符号原文意思的代码，此时第一阶段有实例属性的读操作此时会报错，错误内容大致如下：

**Variable 'self.have' used before being initialized**

**Comment by xiaoLit** [comment]
> 属性不能读取，可以赋值。所以你这里第一行的赋值能执行是没问题的。
> 至于读取，你这种写法读取的应该不是`self.have`，是`init()`传入的参数`have`，所以没有问题，这不是读取实例属性。如果改成`"test\(self.have)"`应该就不行了。

![image](https://user-images.githubusercontent.com/13831437/61265363-63b7e180-a7c2-11e9-8732-3a7e3e9bcc2d.png)
是我图片贴的不妥当了   但确实是可以访问的

**Comment by xiaoLit** [comment]
> @xiaoLit 原文没错，你的例子是错的。
> 
> 实例代码中
> 
> ```
> self.have = have 
> ```
> 
> 不是实例方法，也不是实例属性的读操作而是赋值操作。如果你把代码改成:
> 
> ```
> class tree {
>     var num: Int?
>     var name: String
>     init(name: String) {
>         self.name = name
>     }
> }
> 
> class appleTree: tree {
>     var have: Bool
>     init(name: String, num: Int, have: Bool) {
>         let temp = self.have
>         super.init(name: name)
>     }
> }
> ```
> 
> 此时才是符号原文意思的代码，此时第一阶段有实例属性的读操作此时会报错，错误内容大致如下：
> 
> **Variable 'self.have' used before being initialized**

你理解错我说的重点了  
![image](https://user-images.githubusercontent.com/13831437/61265398-8f3acc00-a7c2-11e9-8156-3f928c01ca45.png)
重点是这部分，这是可以访问的值的 打印出来“testtrue” 。上面那句赋值只不过为了说明，是这个实例变量被初始化后就可以被访问了这个结论

**Comment by BigNerdCoding** [comment]
> > @xiaoLit 原文没错，你的例子是错的。
> > 实例代码中
> > ```
> > self.have = have 
> > ```
> > 
> > 
> > 不是实例方法，也不是实例属性的读操作而是赋值操作。如果你把代码改成:
> > ```
> > class tree {
> >     var num: Int?
> >     var name: String
> >     init(name: String) {
> >         self.name = name
> >     }
> > }
> > 
> > class appleTree: tree {
> >     var have: Bool
> >     init(name: String, num: Int, have: Bool) {
> >         let temp = self.have
> >         super.init(name: name)
> >     }
> > }
> > ```
> > 
> > 
> > 此时才是符号原文意思的代码，此时第一阶段有实例属性的读操作此时会报错，错误内容大致如下：
> > **Variable 'self.have' used before being initialized**
> 
> 你理解错我说的重点了
> ![image](https://user-images.githubusercontent.com/13831437/61265398-8f3acc00-a7c2-11e9-8156-3f928c01ca45.png)
> 重点是这部分，这是可以访问的值的 打印出来“testtrue” 。上面那句赋值只不过为了说明，是这个实例变量被初始化后就可以被访问了这个结论

你可以尝试去掉你的第一个赋值语句，你看是否还能打印

**Comment by BigNerdCoding** [comment]
> > @xiaoLit 原文没错，你的例子是错的。
> > 实例代码中
> > ```
> > self.have = have 
> > ```
> > 
> > 
> > 不是实例方法，也不是实例属性的读操作而是赋值操作。如果你把代码改成:
> > ```
> > class tree {
> >     var num: Int?
> >     var name: String
> >     init(name: String) {
> >         self.name = name
> >     }
> > }
> > 
> > class appleTree: tree {
> >     var have: Bool
> >     init(name: String, num: Int, have: Bool) {
> >         let temp = self.have
> >         super.init(name: name)
> >     }
> > }
> > ```
> > 
> > 
> > 此时才是符号原文意思的代码，此时第一阶段有实例属性的读操作此时会报错，错误内容大致如下：
> > **Variable 'self.have' used before being initialized**
> 
> 你理解错我说的重点了
> ![image](https://user-images.githubusercontent.com/13831437/61265398-8f3acc00-a7c2-11e9-8156-3f928c01ca45.png)
> 重点是这部分，这是可以访问的值的 打印出来“testtrue” 。上面那句赋值只不过为了说明，是这个实例变量被初始化后就可以被访问了这个结论

你的赋值操作就是 appleTree 的第一阶段构造过程，所以你接下来的 print 操作就是在第一阶段后的操作

**Comment by BigNerdCoding** [comment]
> > @xiaoLit 原文没错，你的例子是错的。
> > 实例代码中
> > ```
> > self.have = have 
> > ```
> > 
> > 
> > 不是实例方法，也不是实例属性的读操作而是赋值操作。如果你把代码改成:
> > ```
> > class tree {
> >     var num: Int?
> >     var name: String
> >     init(name: String) {
> >         self.name = name
> >     }
> > }
> > 
> > class appleTree: tree {
> >     var have: Bool
> >     init(name: String, num: Int, have: Bool) {
> >         let temp = self.have
> >         super.init(name: name)
> >     }
> > }
> > ```
> > 
> > 
> > 此时才是符号原文意思的代码，此时第一阶段有实例属性的读操作此时会报错，错误内容大致如下：
> > **Variable 'self.have' used before being initialized**
> 
> 你理解错我说的重点了
> ![image](https://user-images.githubusercontent.com/13831437/61265398-8f3acc00-a7c2-11e9-8156-3f928c01ca45.png)
> 重点是这部分，这是可以访问的值的 打印出来“testtrue” 。上面那句赋值只不过为了说明，是这个实例变量被初始化后就可以被访问了这个结论

我的理解是：子类的第一阶段是：子类初始化完成了内存分配然后初始化了存储属性，super 其实是进行父类的初始化然后内部有父类的第一阶段的构造安全检查，安全检查也是一个层层传递过程。

**Comment by BigNerdCoding** [comment]
@xiaoLit 例如这种代码就无法编译：

```
class tree {
    var num: Int?
    var name: String
    init(name: String) {
        self.name = name
    }
}

class appleTree: tree {
    var have: Bool
    init(name: String, num: Int, have: Bool) {
        self.have = have
        let testStr = "test\(self.have)"
        let testStr2 = "test \(self.name)"
        super.init(name: name)
    }
}
```

self.name 在父类中进行内存分配和赋值初始化过程完成第一阶段的，所以在 super.init 之前访问会有问题

**Comment by xiaoLit** [comment]
> @xiaoLit 例如这种代码就无法编译：
> 
> ```
> class tree {
>     var num: Int?
>     var name: String
>     init(name: String) {
>         self.name = name
>     }
> }
> 
> class appleTree: tree {
>     var have: Bool
>     init(name: String, num: Int, have: Bool) {
>         self.have = have
>         let testStr = "test\(self.have)"
>         let testStr2 = "test \(self.name)"
>         super.init(name: name)
>     }
> }
> ```
> 
> self.name 在父类中进行内存分配和赋值初始化过程完成第一阶段的，所以在 super.init 之前访问会有问题

你似乎没有理解何为第一阶段，什么时候完成进入第二阶段，又不太懂编译器的四部检验，你可以详细的看一下官文的文档关于《构造过程》的内容，然后再来和我讨论。

**Comment by BigNerdCoding** [comment]
> > @xiaoLit 例如这种代码就无法编译：
> > ```
> > class tree {
> >     var num: Int?
> >     var name: String
> >     init(name: String) {
> >         self.name = name
> >     }
> > }
> > 
> > class appleTree: tree {
> >     var have: Bool
> >     init(name: String, num: Int, have: Bool) {
> >         self.have = have
> >         let testStr = "test\(self.have)"
> >         let testStr2 = "test \(self.name)"
> >         super.init(name: name)
> >     }
> > }
> > ```
> > 
> > 
> > self.name 在父类中进行内存分配和赋值初始化过程完成第一阶段的，所以在 super.init 之前访问会有问题
> 
> 你似乎没有理解何为第一阶段，什么时候完成进入第二阶段，又不太懂编译器的四部检验，你可以详细的看一下官文的文档关于《构造过程》的内容，然后再来和我讨论。

@xiaoLit 

官方原文：

> Class initialization in Swift is a two-phase process. In the first phase, each stored property is assigned an initial value by the class that introduced it. Once the initial state for every stored property has been determined, the second phase begins, and each class is given the opportunity to customize its stored properties further before the new instance is considered ready for use.

这段内容我的理解：第一阶段是该类自己生命的存储属性完成默认值赋值后结束，第二阶段开始。那么你构造字符串的时候应该是第二阶段开始了。那么你认为的第一阶段是在什么时候结束的呢？super.init 调用结束吗？

**Comment by BigNerdCoding** [comment]
> > @xiaoLit 例如这种代码就无法编译：
> > ```
> > class tree {
> >     var num: Int?
> >     var name: String
> >     init(name: String) {
> >         self.name = name
> >     }
> > }
> > 
> > class appleTree: tree {
> >     var have: Bool
> >     init(name: String, num: Int, have: Bool) {
> >         self.have = have
> >         let testStr = "test\(self.have)"
> >         let testStr2 = "test \(self.name)"
> >         super.init(name: name)
> >     }
> > }
> > ```
> > 
> > 
> > self.name 在父类中进行内存分配和赋值初始化过程完成第一阶段的，所以在 super.init 之前访问会有问题
> 
> 你似乎没有理解何为第一阶段，什么时候完成进入第二阶段，又不太懂编译器的四部检验，你可以详细的看一下官文的文档关于《构造过程》的内容，然后再来和我讨论。

@xiaoLit 

四步检查依次为：

1. 在调用父类 init 方法之前初始化子类自己声明的属性
2. 在设置继承而来的属性之前需要先调用父类 init 方法，防止误覆盖
3. 在 convenience  构造中设置任意属性之前需要先调用指定构造器，也是防止属性值误覆盖
4. 为了保证初始化工作的完整，强制要求类自己声明的属性在访问之前先出初始化（也就是访问需要在第一阶段后）

不知道这个四步检查理解有没有问题？

你理解的第一阶段是什么时候结束，第二阶段又是什么时候开始的呢？四步检查又各是何种操作？

**Comment by xiaoLit** [comment]
> > > @xiaoLit 例如这种代码就无法编译：
> > > ```
> > > class tree {
> > >     var num: Int?
> > >     var name: String
> > >     init(name: String) {
> > >         self.name = name
> > >     }
> > > }
> > > 
> > > class appleTree: tree {
> > >     var have: Bool
> > >     init(name: String, num: Int, have: Bool) {
> > >         self.have = have
> > >         let testStr = "test\(self.have)"
> > >         let testStr2 = "test \(self.name)"
> > >         super.init(name: name)
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > > self.name 在父类中进行内存分配和赋值初始化过程完成第一阶段的，所以在 super.init 之前访问会有问题
> > 
> > 
> > 你似乎没有理解何为第一阶段，什么时候完成进入第二阶段，又不太懂编译器的四部检验，你可以详细的看一下官文的文档关于《构造过程》的内容，然后再来和我讨论。
> 
> @xiaoLit
> 
> 四步检查依次为：
> 
> 1. 在调用父类 init 方法之前初始化子类自己声明的属性
> 2. 在设置继承而来的属性之前需要先调用父类 init 方法，防止误覆盖
> 3. 在 convenience  构造中设置任意属性之前需要先调用指定构造器，也是防止属性值误覆盖
> 4. 为了保证初始化工作的完整，强制要求类自己声明的属性在访问之前先出初始化（也就是访问需要在第一阶段后）
> 
> 不知道这个四步检查理解有没有问题？
> 
> 你理解的第一阶段是什么时候结束，第二阶段又是什么时候开始的呢？四步检查又各是何种操作？

不是我理解什么就是什么，是人家官方文档上写的。而且你根本没懂我说的是什么问题，你举例的也只是四步检验中必要的环节，而我说的完全和它没关系，麻烦真的好好看一下官方文档何为构造一二阶段，你的理解很多都是错的。

**Comment by xiaoLit** [comment]
而且仔细看一下我说的是什么问题！

**Comment by BigNerdCoding** [comment]
> 仔细看一下我说的是什么问题！

@xiaoLit 

你的第一字符串访问处于什么阶段，根据官方文档。如果处于第一阶段则你说的是对的，如果第一阶段已经结束那么与第四步就不冲突。官方原文第一阶段应该是在该类自己声明属性初始话结束后就结束了。

你可以说下你的理解啊，你的理解是官方第四步安全检查描述和代码是有冲突的，不绝对的。那么你的理解是，你代码中打印字符串的操作处于第一阶段，也就是此时第一阶段没有结束。

然而根据上述官方原文，子类自己声明存储属性赋值初始化结束就完成了第一阶段。

如果我的理解错了话，你可以用更简单的话描述一下你这里的不绝对是什么意思吗？打印操作和第四步安全检查冲突在何处。

**Comment by xiaoLit** [comment]
> > 仔细看一下我说的是什么问题！
> 
> @xiaoLit
> 
> 你的第一字符串访问处于什么阶段，根据官方文档。如果处于第一阶段则你说的是对的，如果第一阶段已经结束那么与第四步就不冲突。官方原文第一阶段应该是在该类自己声明属性初始话结束后就结束了。
> 
> 你可以说下你的理解啊，你的理解是官方第四步安全检查描述和代码是有冲突的，不绝对的。那么你的理解是，你代码中打印字符串的操作处于第一阶段，也就是此时第一阶段没有结束。
> 
> 然而根据上述官方原文，子类自己声明存储属性赋值初始化结束就完成了第一阶段。
> 
> 如果我的理解错了话，你可以用更简单的话描述一下你这里的不绝对是什么意思吗？打印操作和第四步安全检查冲突在何处。

怎么都不看我说的呢，然后还不好好看文档！
![image](https://user-images.githubusercontent.com/13831437/61277040-e0a78300-a7e3-11e9-85c2-0121fb47b29c.png)
仔细看第一阶段包含什么，这不是我加以的理解，是完完全全官方的言论，在不懂官方文档说的话之前不要自己理解好吧。首先简单的说向上的构造代理过程都处于第一阶段，所以红框里面的代码处于第一阶段不需要额外解释了吧！

**Comment by xiaoLit** [comment]
而且不存在什么子类初始化，父类再初始化的任何概念。不要加以臆想。这是一个实例对象的创建！

**Comment by BigNerdCoding** [comment]
> 而且不存在什么子类初始化，父类再初始化的任何概念。不要加以臆想。这是一个实例对象的构造过程！

@xiaoLit 
>Class initialization in Swift is a two-phase process. In the first phase, **each stored property is assigned an initial value by the class that introduced it**. **Once the initial state for every stored property has been determined, the second phase begins**, and each class is given the opportunity to customize its stored properties further before the new instance is considered ready for use.

官方原文请再看一下

**Comment by BigNerdCoding** [comment]
@xiaoLit 

你可以给 Apple 官方的 Swift 开发者发邮件说出你的理解指出问题所在。

**Comment by xiaoLit** [comment]
哎... 真牛逼

**Comment by BigNerdCoding** [comment]
> 哎... 真牛逼

这个地方确实有问题，建议你找 Apple 官方反馈下，如果有更多内容翻译组会同步更新翻译。

**Comment by xiaoLit** [comment]
> > 哎... 真牛逼
> 
> @xiaoLit
> 
> 这个地方确实有问题，建议你找 Apple 官方反馈下，如果有更多内容翻译组会同步更新翻译。

不知道哪能和他们直接交流上呢，github上swift项目只能提request。
