### ISSUE TITLE
访问控制-翻译问题

### ISSUE THREAD

**Issue by Robinguo2012** [SwiftGGTeam/the-swift-programming-language-in-chinese#972]
`可以通过重写为继承来的类成员提供更高的访问级别。`
将file-private 重新指定为internal，写成了private。

`也就是说，在同一源文件中访问父类 private 级别的成员，在同一模块内访问父类 internal 级别的成员`
应该是子类访问父类的file-private级别的成员，写成了private级别。

**Comment by numbbbbb** [comment]
已修改，感谢指正！
